### PR TITLE
Add solution "Checkpoints"

### PR DESCRIPTION
**Pull request by fia0**
Not quite down yet, the atomic checkpoints are missing, the statistics at the end and some explanations to choices made.

### CODE REVIEW

**Comment by fia0** [comment]
I just added the atomic writing of checkpoints, with a short blurp to why and what in the source file. Though this would have to be moved to the specific file and worked out a bit more

**Comment by fia0** [comment]
Should be completed now, as last option I added some atomic counters to track the operations and throughput

**Comment by fia0** [comment]
Looking to merge around 9 pm, if you all can have a quick look before then

**Review by SkyRiderSCII — APPROVED** [review]

**Review by darshit-97 — APPROVED** [review]

**Comment by fia0** [comment]
Merge due to date

**Pull request merged**
